import Head from 'next/head'
import Hero from "@/Component/Hero";
import Address from "@/Component/Address";
import CheckBal from "@/Component/CheckBal";
import Header from "@/Component/utils/Header";
import {useRouter} from "next/router";
import {useEffect} from "react";


export default function Home() {
    const router = useRouter()
    // this here is reponsible for restoring the user's scroll position
    useEffect(() => {
        const handleRouteChange = () => {
            localStorage.setItem('scrollPosition', window.scrollY.toString());
        };

        router.events.on('routeChangeStart', handleRouteChange);

        const storedScrollPosition = localStorage.getItem('scrollPosition');
        const timeout = setTimeout(() => {
            if (storedScrollPosition) {
                window.scrollTo(0, parseInt(storedScrollPosition));
            }
        },100)
        return () => {
            router.events.off('routeChangeStart', handleRouteChange);
            clearTimeout(timeout)
        };
    }, []);


    return (
    <>
        <Header title={'OriginTrail challenge'} description={'this website is created my samuel'} content={'Generated by create next app'}/>
        <Hero/>
        <Address/>
      <CheckBal/>
    </>
  )
}
