import Head from 'next/head'
import Nav from "@/Component/Layout/Nav";
import Hero from "@/Component/Hero";
import Address from "@/Component/Address";

import CheckBal from "@/Component/CheckBal";
import TransactionDetailsCard from "@/Component/utils/TransactionDetailCard";
import Header from "@/Component/utils/Header";


export default function Home() {
  return (
    <>
        <Header title={'OriginTrail challenge'} description={'this website is created my samuel'} content={'Generated by create next app'}/>
        <Hero/>
        <Address/>
      <CheckBal/>
    </>
  )
}
